name: Manual System Health Check

on:
  workflow_dispatch:  # Allows manual execution via GitHub Actions

jobs:
  run-health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run system health check script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python main.py

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: system_health_report
          path: system_health_report.pdf
